language: ruby
rvm:
  - "1.9.3"
#  - "2.1.5"
#  - rbx
#  - rbx-2
install: gem install activesupport -v 4.2.6 && gem install gem install mime-types -v 2.6.2 && gem install rest-client shoulda minitest
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script: echo "y" | rake test
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always

