language: ruby
rvm:
  - "1.9.3"
#  - "2.1.5"
#  - rbx
#  - rbx-2
install: gem install rest-client shoulda
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script: cd ruby && echo "y" | rake test

